name: citiguide
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  cached_network_image: ^3.3.1
  firebase_auth:
  firebase_core: ^2.24.2
  firebase_database:
  custom_searchable_dropdown: ^2.1.1
  url_launcher: ^6.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
